name: Контроль качества

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  sonar:
    if: (github.repository == 'Segate-ekb/vanessa-runner') && (github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.event.repository.full_name)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        oscript_version: ['stable']
        v8_version: ['8.3.23.1997']   
    steps:
      - name: Актуализация
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Вычисление имени ветки
        uses: nelonoel/branch-name@v1.0.1
        
      - name: Извлечение версии пакета
        shell: bash
        run: echo "version=`cat packagedef | grep ".Версия(" | sed 's|[^"]*"||' | sed -r 's/".+//'`" >> $GITHUB_OUTPUT
        id: extract_version

      - name: Настройка sonar-scanner
        uses: warchant/setup-sonar-scanner@v8

      - name: Анализ в SonarQube (branch)
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: sonar-scanner
          -Dsonar.host.url=https://sonar.1cdevelopers.ru/
          -Dsonar.branch.name=${{ env.BRANCH_NAME }}
          -Dsonar.projectVersion=${{ steps.extract_version.outputs.version }}

      # https://docs.sonarqube.org/latest/analysis/pull-request/
      - name: Анализ в SonarQube (pull-request)
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: sonar-scanner
          -Dsonar.host.url=https://sonar.1cdevelopers.ru/
          -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
          -Dsonar.pullrequest.branch=${{ github.event.pull_request.head.ref }}
          -Dsonar.pullrequest.base=${{ github.event.pull_request.base.ref }}
          -Dsonar.scm.revision=${{ github.event.pull_request.head.sha }}