name: Тестирование

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        oscript_version: ['stable']
        v8_version: ['8.3.23.1997']
        os: [ 'windows-latest']    
    steps:
      - name: Актуализация
        uses: actions/checkout@v4

      - name: Установка свойств git
        shell: bash
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      
      - name: Вычисление версии OneScript
        shell: bash
        id: extract_oscript_version
        run: |
          set -ex
          if [ "${{ matrix.oscript_version }}" = "default" ]
          then
            extracted_version=$(cat packagedef | grep ".ВерсияСреды(" | sed 's|[^"]*"||' | sed -r 's/".+//' || true)
            version="${extracted_version:-stable}"
          else
            version="${{ matrix.oscript_version }}"
          fi
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Установка OneScript
        uses: otymko/setup-onescript@v1.4
        with:
          version: ${{ steps.extract_oscript_version.outputs.version }}

      - name: Установка зависимостей
        run: |
          opm install opm
          opm install -l --dev
      
      - name: Установка дополнительных пакетов
        run: opm install add

      - name: Установка 1С:Предприятие
        if: matrix.v8_version != ''
        uses: 1CDevFlow/onec-setup-action@main
        with:
          type: onec # Тип устанавливаемого приложения
          onec_version: ${{ matrix.v8_version }}
          cache: false
        env: 
          ONEC_USERNAME: ${{ secrets.ONEC_USERNAME }}
          ONEC_PASSWORD: ${{ secrets.ONEC_PASSWORD }} 
  
      - name: Установка лицензии (Windows)
        if: matrix.v8_version != '' && matrix.os == 'windows-latest'
        run: |
            mkdir "C:\ProgramData\1C\licenses" -Force
            echo $Env:ONEC_LICENCE | Out-File -FilePath "C:\ProgramData\1C\licenses\licence.lic" -Encoding ascii
        shell: pwsh
        env:
            ONEC_LICENCE: ${{ secrets.ONEC_LICENCE }}

      - name: Отключение защиты от опасных действий
        if: matrix.v8_version != '' && matrix.os == 'windows-latest'
        run: |
              New-Item -ItemType Directory -Force -Path "C:\Program Files\1cv8\conf"
              Set-Content -Path "C:\Program Files\1cv8\conf\conf.cfg" -Value @'
              DisableUnsafeActionProtection=.*
              SystemLanguage=System
              '@
        shell: pwsh 

      - name: Тестирование
        shell: cmd
        run: oscript ./tasks/test.os

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/bdd-exec.xml'  